### ISSUE TITLE
Add Bin files support

### ISSUE THREAD

**Issue by venterum** [M-L-P/grub2-brunch#2]
Hi there, Thank you for your product. However, there is one issue I would like to bring to your attention. When I was installing ChromeOS, I created the chromeos.bin and chromeos.bin.grub.txt files, which are not *.img as you see. As a result, I am unable to use this great and convenient software. Could you please add *.bin files support? I would greatly appreciate it.

**Comment by 1457384613gh** [comment]
How have you got `chromeos.bin.grub.txt`?

**Comment by venterum** [comment]
> How have you got `chromeos.bin.grub.txt`?

Did all instructions from brunch github page and got `*.bin` files. Actually, they are mentioned with this extention in the `Install Brunch with Windows` so I guess it is ok

**Comment by venterum** [comment]
Maybe I did something wrong but my ChromeOS works good all this time

**Comment by 1457384613gh** [comment]
Give a screenshot of instruction and another of `chromeos.bin.grub.txt`.

**Comment by venterum** [comment]
Hmm, I just checked the final steps of the instructions and there are `.img` files XD

Here is my `chromeos.bin.grub.txt`

```
menuentry "Brunch" --class "brunch" {
	img_path=/brunch/chromeos.bin
	img_uuid=88aaa6ff-5998-4abe-9ea5-483195c20b5f
	search --no-floppy --set=root --file $img_path
	loopback loop $img_path
	source (loop,12)/efi/boot/settings.cfg
	if [ -z $verbose ] -o [ $verbose -eq 0 ]; then
		linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \
			cros_secure cros_debug img_uuid=$img_uuid img_path=$img_path \
			console= vt.global_cursor_default=0 brunch_bootsplash=$brunch_bootsplash quiet
	else
		linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \
			cros_secure cros_debug img_uuid=$img_uuid img_path=$img_path
	fi
	initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img
}

menuentry "Brunch settings" --class "brunch-settings" {
	img_path=/brunch/chromeos.bin
	img_uuid=88aaa6ff-5998-4abe-9ea5-483195c20b5f
	search --no-floppy --set=root --file $img_path
	loopback loop $img_path
	source (loop,12)/efi/boot/settings.cfg
	linux (loop,7)/kernel boot=local noresume noswap loglevel=7 options= chromeos_bootsplash= edit_brunch_config=1 \
		cros_secure cros_debug img_uuid=$img_uuid img_path=$img_path
	initrd (loop,7)/lib/firmware/amd-ucode.img (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img
}
```

**Comment by venterum** [comment]
I guess i did something wrong, so i should somehow repack my `chromeos.bin` to `chromeos.img`

**Comment by 1457384613gh** [comment]
Did you enter `sudo bash chromeos-install.sh -src chromeos_filename.bin -dst ~/tmpmount/chromeos.bin -s size`?

Rename those two files and try.

**Comment by venterum** [comment]
> Did you enter `sudo bash chromeos-install.sh -src chromeos_filename.bin -dst ~/tmpmount/chromeos.bin -s size`?

I guess so and that caused the wrong extension

**Comment by venterum** [comment]
> Rename those two files and try.

Worked! Thanks a lot, finally can get rid of Grub2Win!

**Comment by 1457384613gh** [comment]
![Screenshot_2024-06-16-04-20-53-687_com.github.android-edit.jpg](https://github.com/M-L-P/grub2-brunch/assets/69227436/6ff1e2aa-c5c3-45de-b196-cd33af37bce4)

Them, too.

**Comment by venterum** [comment]
> Them

I've already done it, thanks for the help!
