### ISSUE TITLE
Stuck at Brunch Framework logo

### ISSUE THREAD

**Issue by Andrew-Sor** [M-L-P/grub2-brunch#3]
I'm trying to boot Chrome OS via grub2-brunch. But it gets stuck on the Branch logo and "Loading Brunch Framework...".

Can you help me?

**Comment by 1457384613gh** [comment]
You should have entered `Brunch Settings` first.

**Comment by Andrew-Sor** [comment]
> Вы должны были войти первым.`Brunch Settings`

What should I have done there? I specified the path to the img and configuration files.

**Comment by 1457384613gh** [comment]
![Screenshot_2024-12-20-18-23-52-482_com.android.browser-edit.jpg](https://github.com/user-attachments/assets/c737f69b-2edd-4c10-a3c3-45a8b93de14c)

**Comment by Andrew-Sor** [comment]
> ![Screenshot_2024-12-20-18-23-52-482_com.android.browser-edit.jpg](https://private-user-images.githubusercontent.com/69227436/397705310-c737f69b-2edd-4c10-a3c3-45a8b93de14c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2OTIyODYsIm5iZiI6MTczNDY5MTk4NiwicGF0aCI6Ii82OTIyNzQzNi8zOTc3MDUzMTAtYzczN2Y2OWItMmVkZC00YzEwLWEzYzMtNDVhOGI5M2RlMTRjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDEwNTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZWE0ZmYxN2FlMTRiOTY4YzUxYjJlN2IxNjYwNzk1MDY3N2JhYTY4N2M3MGJmOGM5ZTE2Zjg5NjRlODZlZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Jq34ELZITBXGTRiPZw23_8HcDYzJgr1ZLT4X0y9OFKA)

I understand. What should I do after I select this item?

**Comment by 1457384613gh** [comment]
https://github.com/sebanc/brunch/blob/main/Readme/troubleshooting-and-faqs.md

**Comment by Andrew-Sor** [comment]
> https://github.com/sebanc/brunch/blob/main/Readme/troubleshooting-and-faqs.md

My problem is not there

**Comment by Andrew-Sor** [comment]
By the way. I wrote this image to a flash drive and Chrome OS booted from it normally.

**Comment by Andrew-Sor** [comment]
I found a solution to the problem.
